import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// Cargando e instanciando la fuente optimizada Inter
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className="h-full antialiased">
      {/* Aplicando la fuente Inter al body */}
      <body className={`${inter.className} min-h-full flex flex-col bg-white dark:bg-black`}>
        {children}
      </body>
    </html>
  );
}
